export let WordLists = {
	"Home Life 1": [
		{ "english": "apple", "pinyin": "píng guǒ", "chinese": "苹果", "pic": "apple.jpg" },
		{ "english": "ball", "pinyin": "qiú", "chinese": "球", "pic": "ball.jpg" },
		{ "english": "banana", "pinyin": "xiāng jiāo", "chinese": "香蕉", "pic": "banana.jpg" },
		{ "english": "bed", "pinyin": "chuáng", "chinese": "床", "pic": "bed.jpg" },
		{ "english": "bike", "pinyin": "zì xíng chē", "chinese": "自行车", "pic": "bike.jpg" },
		{ "english": "car", "pinyin": "qì chē", "chinese": "汽车", "pic": "car.jpg", "cl": "辆" },
		{ "english": "chair", "pinyin": "yǐ zi", "chinese": "椅子", "pic": "chair.jpg" },
		{ "english": "dirty", "pinyin": "zāng", "chinese": "脏", "pic": "dirty.png" },		
		{ "english": "house", "pinyin": "fáng zi", "chinese": "房子", "pic": "house.jpg", "cl": "座" },
		{ "english": "milk", "pinyin": "niú nǎi", "chinese": "牛奶", "pic": "milk.jpg" },
		{ "english": "phone", "pinyin": "diàn huà", "chinese": "电话", "pic": "phone.jpg" },
		{ "english": "piano", "pinyin": "gāng qín", "chinese": "钢琴", "pic": "piano.jpg" },
		{ "english": "shoes", "pinyin": "xié zi", "chinese": "鞋子", "pic": "shoes.jpg" },
		{ "english": "tomato", "pinyin": "xī hóng shì", "chinese": "西红柿", "pic": "tomato.jpg" },
		{ "english": "toy", "pinyin": "wán jù", "chinese": "玩具", "pic": "toy.jpg" },
	],
	"Home Life 2": [
		{ "english": "airplane", "pinyin": "fēi jī", "chinese": "飞机", "pic": "airplane.jpg" },
		{ "english": "guitar", "pinyin": "jí tā", "chinese": "吉他", "pic": "guitar.jpg" },		
	],	
	"Food": [
		{ "english": "grapes", "pinyin": "pú táo", "chinese": "葡萄", "pic": "grapes.jpg" },
		{ "english": "ice cream", "pinyin": "bīng qí lín", "chinese": "冰淇淋", "pic": "icecream.jpg" },
		{ "english": "apple", "pinyin": "píng guǒ", "chinese": "苹果", "pic": "apple.jpg" },
		{ "english": "egg", "pinyin": "jī dàn", "chinese": "鸡蛋", "pic": "egg.jpg" },
		{ "english": "cake", "pinyin": "dàn gāo", "chinese": "蛋糕", "pic": "cake.jpg", "cl": "块" },
		{ "english": "banana", "pinyin": "xiāng jiāo", "chinese": "香蕉", "pic": "banana.jpg" },
		{ "english": "tomato", "pinyin": "xī hóng shì", "chinese": "西红柿", "pic": "tomato.jpg" },
		{ "english": "bacon", "pinyin": "péi gēn", "chinese": "培根", "pic": "bacon.jpg" },
		{ "english": "cookie", "pinyin": "bǐng gān", "chinese": "饼干", "pic": "cookie.jpg" },
		{ "english": "bread", "pinyin": "miàn bāo", "chinese": "面包", "pic": "bread.jpg", "cl": "片" },
		{ "english": "potato soup", "pinyin": "tǔ dòu tāng", "chinese": "土豆汤", "pic": "potatosoup.jpg" },
		{ "english": "sushi", "pinyin": "shòu sī", "chinese": "寿司", "pic": "sushi.jpg" },
		{ "english": "ramen", "pinyin": "lā miàn", "chinese": "拉面", "pic": "ramen.jpg" },
		{ "english": "applesauce", "pinyin": "píng guǒ ní", "chinese": "苹果泥", "pic": "applesauce.jpg" },
		{ "english": "corn dogs", "pinyin": "yù mǐ gǒu", "chinese": "玉米狗", "pic": "corndog.png" },
	],
	"Cooking": [
		{ "english": "rice", "pinyin": "fàn", "chinese": "饭" },
		{ "english": "noodles", "pinyin": "miàn", "chinese": "面" },
		{ "english": "beef", "pinyin": "niú ròu", "chinese": "牛肉" },
		{ "english": "chicken", "pinyin": "jī ròu", "chinese": "鸡肉" },
		{ "english": "pork", "pinyin": "zhū ròu", "chinese": "猪" },
		{ "english": "tea", "pinyin": "chá", "chinese": "茶" },
		{ "english": "vegetables", "pinyin": "cài", "chinese": "菜" },
		{ "english": "soy milk", "pinyin": "dòu jiāng", "chinese": "豆浆" },
		{ "english": "oil", "pinyin": "yóu", "chinese": "油" },
		{ "english": "tofu", "pinyin": "dòu fu", "chinese": "豆腐" },
		{ "english": "onion", "pinyin": "cōng", "chinese": "葱" },
		{ "english": "potato", "pinyin": "tǔ dòu", "chinese": "土豆" },
		{ "english": "spicy", "pinyin": "là", "chinese": "辣" },
		{ "english": "sweet", "pinyin": "tián", "chinese": "甜" },
		{ "english": "soy sauce", "pinyin": "jiàng yóu", "chinese": "酱油" },
	],
	"Animals 1": [
		{ "english": "deer", "pinyin": "lù", "chinese": "鹿", "pic": "deer.jpg", "cl": "只" },
		{ "english": "cow", "pinyin": "niú", "chinese": "牛", "pic": "cow.jpg", "cl": "只" },
		{ "english": "pig", "pinyin": "zhū", "chinese": "猪", "pic": "pig.jpg", "cl": "只" },
		{ "english": "fish", "pinyin": "yú", "chinese": "鱼", "pic": "fish.jpg" },
		{ "english": "snake", "pinyin": "shé", "chinese": "蛇", "pic": "snake.jpg" },
		{ "english": "turtle", "pinyin": "wū guī", "chinese": "乌龟", "pic": "turtle.jpg", "cl": "只" },
		{ "english": "giraffe", "pinyin": "cháng jǐng lù", "chinese": "长颈鹿", "pic": "giraffe.jpg", "cl": "只" },
		{ "english": "cat", "pinyin": "māo", "chinese": "猫", "cl": "只", "pic": "cat.jpg"},
		{ "english": "dog", "pinyin": "gǒu", "chinese": "狗", "pic": "dog.jpg" },
		{ "english": "elephant", "pinyin": "dà xiàng", "chinese": "大象", "cl": "只", "pic": "elephant.jpg" },
		{ "english": "peregrine falcon", "pinyin": "yóu sǔn", "chinese": "游隼", "pic": "pfalcon.jpg", "cl": "只" },
		{ "english": "panda", "pinyin": "xióng māo", "chinese": "熊猫", "pic": "panda.jpg", "cl": "只" },
		{ "english": "cheetah", "pinyin": "liè bào", "chinese": "猎豹", "pic": "cheetah.jpg", "cl": "只" },
	],
	"Animals 2": [
		{ "english": "zebra", "pinyin": "bān mǎ", "chinese": "斑马", "pic": "zebra.png" },
		{ "english": "bear", "pinyin": "xióng", "chinese": "熊", "pic": "bear.jpg", "cl": "只" },
		{ "english": "rabbit", "pinyin": "tù zi", "chinese": "兔子", "pic": "rabbit.jpg", "cl": "只" },
		{ "english": "alien", "pinyin": "wài xīng rén", "chinese": "外星人", "pic": "alien.jpg", "cl": "位" },
		{ "english": "horse", "pinyin": "mǎ", "chinese": "马", "pic": "horse.jpg", "cl": "匹" },
		{ "english": "bird", "pinyin": "niǎo", "chinese": "鸟", "pic": "bird.jpg", "cl": "只" },
		{ "english": "duck", "pinyin": "yā zi", "chinese": "鸭子", "pic": "duck.jpg", "cl": "只" },
		{ "english": "chicken", "pinyin": "jī", "chinese": "鸡", "pic": "chicken.jpg", "cl": "只" },
		{ "english": "sheep", "pinyin": "miàn yáng", "chinese": "绵羊", "pic": "sheep.jpg", "cl": "只" },
		{ "english": "frog", "pinyin": "qīng wā", "chinese": "青蛙", "pic": "frog.jpg", "cl": "只" },
		{ "english": "monkey", "pinyin": "hóu zi", "chinese": "猴子", "pic": "monkey.jpg", "cl": "只" },
		{ "english": "dolphin", "pinyin": "hǎi tún", "chinese": "海豚", "pic": "dolphin.jpg" },
		{ "english": "koala", "pinyin": "kǎo lā", "chinese": "考拉", "pic": "koala.jpg", "cl": "只" },
	],
	"Nouns": [
		{ "english": "house", "pinyin": "fáng zi", "chinese": "房子", "pic": "house.jpg", "cl": "座" },
		{ "english": "flower", "pinyin": "huā", "chinese": "花", "pic": "flower.jpg", "cl": "朵" },
		{ "english": "kitchen", "pinyin": "chú fáng", "chinese": "厨房", "pic": "kitchen.jpg" },
		{ "english": "sun", "pinyin": "tài yáng", "chinese": "太阳", "pic": "sun.jpg" },
		{ "english": "kite", "pinyin": "fēng zheng", "chinese": "风筝", "pic": "kite.jpg" },
		{ "english": "star", "pinyin": "xīng", "chinese": "星", "pic": "star.png", "cl": "个" },
		{ "english": "car", "pinyin": "qì chē", "chinese": "汽车", "pic": "car.jpg", "cl": "辆" },
		{ "english": "head", "pinyin": "tóu", "chinese": "头", "pic": "head.jpg", "cl": "个" },
		{ "english": "family", "pinyin": "jiā tíng", "chinese": "家庭", "pic": "family.jpg" },
		{ "english": "hand", "pinyin": "shǒu", "chinese": "手", "pic": "hand.jpg", "cl": "只" },
		{ "english": "heart", "pinyin": "xīn", "chinese": "心", "pic": "heart.png" },
		{ "english": "tree", "pinyin": "shù", "chinese": "树", "pic": "tree.jpg", "cl": "棵" },
		{ "english": "living room", "pinyin": "kè tíng", "chinese": "客厅", "pic": "livingroom.jpg" },
		{ "english": "day", "pinyin": "rì", "chinese": "日", "pic": "day.jpg" },
		{ "english": "night", "pinyin": "yè", "chinese": "夜", "pic": "night.jpg" },
		{ "english": "butter knife", "pinyin": "xiǎo dāo", "chinese": "小刀", "pic": "butterknife.jpg", "cl": "把" },
		{ "english": "book", "pinyin": "shū", "chinese": "书", "pic": "book.png", "cl": "本" },
		{ "english": "paper", "pinyin": "zhǐ", "chinese": "纸", "pic": "paper.jpg", "cl": "张" },
	],
	"Adjectives 1": [
		{ "english": "hot", "pinyin": "rè", "chinese": "热", "pic": "hot.jpg" },
		{ "english": "cold", "pinyin": "lěng", "chinese": "冷", "pic": "cold.jpg" },
		{ "english": "clean", "pinyin": "gān jìng", "chinese": "干净", "pic": "clean.jpg" },
		{ "english": "dirty", "pinyin": "zāng", "chinese": "脏", "pic": "dirty.png" },
		{ "english": "happy", "pinyin": "kuài lè", "chinese": "快乐", "pic": "happy.jpg" },
		{ "english": "unhappy", "pinyin": "bú kuài lè", "chinese": "不快乐", "pic": "unhappy.jpg" },
		{ "english": "wet", "pinyin": "shī", "chinese": "湿", "pic": "wet.jpg" },
		{ "english": "dry", "pinyin": "gān", "chinese": "干", "pic": "dry.jpg" },
		{ "english": "young", "pinyin": "nián qīng", "chinese": "年轻", "pic": "young.jpg" },
		{ "english": "old", "pinyin": "lǎo", "chinese": "老", "pic": "old.jpg" },	
	],
	"Adjectives 2": [
		{ "english": "full", "pinyin": "mǎn", "chinese": "满", "pic": "full.gif" },
		{ "english": "empty", "pinyin": "kōng", "chinese": "空", "pic": "empty.jpg" },
		{ "english": "hard", "pinyin": "yìng", "chinese": "硬", "pic": "hard.jpg" },
		{ "english": "soft", "pinyin": "ruǎn", "chinese": "软", "pic": "soft.jpg" },
		{ "english": "big", "pinyin": "dà", "chinese": "大", "pic": "big.png" },
		{ "english": "small", "pinyin": "xiǎo", "chinese": "小", "pic": "small.jpg" },
		{ "english": "short", "pinyin": "duǎn", "chinese": "短", "pic": "short.png" },
		{ "english": "long", "pinyin": "cháng", "chinese": "长", "pic": "long.jpg" },
		{ 'english': "noisy", "pinyin": "chǎo", "chinese": '吵' },
	],
	"Directions": [
		{ "english": "right", "pinyin": "yòu", "chinese": "友", "pic": "right.png" },
		{ "english": "left", "pinyin": "zuǒ", "chinese": "左", "pic": "left.png" },
		{ "english": "out", "pinyin": "wài", "chinese": "外", "pic": "out.jpg" },
		{ "english": "in", "pinyin": "nèi", "chinese": "内", "pic": "in.png" },
		{ "english": "above", "pinyin": "shàng", "chinese": "上" },
		{ "english": "below", "pinyin": "xià", "chinese": "下" },
		{ "english": "front", "pinyin": "qián", "chinese": "前", "pic": "front.png" },
		{ "english": "back", "pinyin": "hòu", "chinese": "后", "pic": "back.png" },
		{ "english": "north", "pinyin": "běi", "chinese": "北", "pic": "north.jpg" },
		{ "english": "east", "pinyin": "dōng", "chinese": "东", "pic": "east.jpg" },
		{ "english": "south", "pinyin": "nán", "chinese": "南", "pic": "south.jpg" },
		{ "english": "west", "pinyin": "xī", "chinese": "西", "pic": "west.jpg" },
		{ "english": "middle", "pinyin": "zhōng", "chinese": "中", "pic": "middle.png" },
		{ "english": "last", "pinyin": "zuì hòu", "chinese": "最后", "pic": "last.jpg" },
		{ "english": "first", "pinyin": "dì yī", "chinese": "第一", "pic": "first.jpg" },		
	],
	"Transitive Verbs": [
		{ "english": "like", "pinyin": "xǐ huān", "chinese": "喜欢" },
		{ "english": "throw", "pinyin": "rēng", "chinese": "扔", "pic": "throw.jpg" },
		{ "english": "see", "pinyin": "kàn", "chinese": "看" },
		{ "english": "have", "pinyin": "yǒu", "chinese": "有" },	
		{ "english": "eat", "pinyin": "chī", "chinese": "吃" },
		{ "english": "need", "pinyin": "xū yào", "chinese": "需要" },
		{ "english": "love", "pinyin": "ài", "chinese": "爱" },
		{ "english": "buy", "pinyin": "mǎi", "chinese": "买" },
		{ "english": "sell", "pinyin": "mài", "chinese": "卖" },
		{ "english": "wash", "pinyin": "xǐ", "chinese": "洗" },
	],
	"Comp T Verbs": [
		{ "english": "eat", "pinyin": "chī", "chinese": "吃" },
		{ "english": "wash", "pinyin": "xǐ", "chinese": "洗" },
		{ "english": "look for", "pinyin": "zhǎo", "chinese": "找" },
		{ "english": "listen", "pinyin": "tīng", "chinese": "听" },
		{ "english": "throw", "pinyin": "rēng", "chinese": "扔", "pic": "throw.jpg" },
		{ "english": "pull", "pinyin": "lā", "chinese": "拉" },
		{ "english": "push", "pinyin": "tuī", "chinese": "推" },
	],
	"Verbs 1": [
		{ "english": "stop", "pinyin": "tíng zhǐ", "chinese": "停止", "pic": "stop.png" },
		{ "english": "go", "pinyin": "qù", "chinese": "去", "pic": "go.jpg" },
		{ "english": "start", "pinyin": "kāi shǐ", "chinese": "开始", "pic": "star.png", "pic": "start.jpg" },
		{ "english": "walk", "pinyin": "zǒu", "chinese": "走", "pic": "walk.jpg" },
		{ "english": "run", "pinyin": "pǎo bù", "chinese": "跑步", "pic": "run.jpg" },
		{ "english": "sleep", "pinyin": "shuì jiào", "chinese": "睡觉", "pic": "sleep.jpg" },
		{ "english": "awake", "pinyin": "xǐng lái", "chinese": "醒来", "pic": "awake.jpg" },
		{ "english": "swim", "pinyin": "yóu yǒng", "chinese": "游泳", "pic": "swim.jpg" },
		{ "english": "cry", "pinyin": "kū", "chinese": "哭", "pic": "cry.jpg" },
		{ "english": "smile", "pinyin": "wēi xiào", "chinese": "微笑", "pic": "smile.jpg" },
		{ "english": "frown", "pinyin": "zhòu méi", "chinese": "皱眉", "pic": "frown.jpg" },
		{ "english": "shake head", "pinyin": "yáo tóu", "chinese": "摇头" },
		{ "english": "laugh", "pinyin": "xiào", "chinese": "笑", "pic": "laugh.jpg" },
		{ "english": "fall down", "pinyin": "dǎo xià", "chinese": "倒下", "pic": "falldown.jpg" },
		{ "english": "close", "pinyin": "guān", "chinese": "关", "pic": "closed.png" },
		{ "english": "open", "pinyin": "kāi", "chinese": "开", "pic": "open.jpg" },		
	],
	"Verbs 2": [
		{ "english": "catch", "pinyin": "zhūa", "chinese": "抓", "pic": "catch.jpg" },
		{ "english": "give", "pinyin": "gěi", "chinese": "给", "pic": "give.jpg" },
		{ "english": "read", "pinyin": "dú", "chinese": "读", "pic": "read.jpg" },
		{ "english": "look", "pinyin": "kàn", "chinese": "看", "pic": "look.jpg" },
		{ "english": "come", "pinyin": "lái", "chinese": "来" },
		{ "english": "jump", "pinyin": "tiào", "chinese": "跳", "pic": "jump.jpg" },
		{ "english": "stand", "pinyin": "zhàn", "chinese": "站" },
		{ "english": "return", "pinyin": "huí lái", "chinese": "回来" },
		{ "english": "turn", "pinyin": "zhǔan", "chinese": "转" },
		{ "english": "clap", "pinyin": "pāi shǒu", "chinese": "拍手", "pic": "clap.jpg" },
		{ "english": "shake hands", "pinyin": "wò shǒu", "chinese": "握手", "pic": "shakehands.jpg" },
		{ "english": "raise hand", "pinyin": "jǔ shǒu", "chinese": "举手", "pic": "raisehand.jpg" },
		{ "english": "point", "pinyin": "zhǐ", "chinese": "指" },
		{ "english": "sit", "pinyin": "zuò", "chinese": "坐", "pic": "sit.jpg" },
	],
	"Famous People": [
		{ "english": "Kim Jong-un", "pinyin": "jīn zhèng ēn", "chinese": "金正恩", "pic": "kju.jpg" },
		{ "english": "Confucius", "pinyin": "kǒng zǐ", "chinese": "孔子", "pic": "kongzi.jpg" },
		{ "english": "Trump", "pinyin": "tè lǎng pǔ", "chinese": "特朗普", "pic": "trump.jpg" },
		/*{ "english": "Clinton", "pinyin": "kè lín dùn", "chinese": "克林顿", "pic": "hclinton.jpg" },*/
		{ "english": "Mao Zedong", "pinyin": "máo zé dōng", "chinese": "毛泽东", "pic": "maozedong.jpg" },
		{ "english": "Xi Jinping", "pinyin": "xí jìn píng", "chinese": "习近平", "pic": "xijinping.jpg" },
		{ "english": "Bruce Lee", "pinyin": "lǐ xiǎo lóng", "chinese": "李小龙", "pic": "brucelee.jpg" },
		{ "english": "Sun Tzu", "pinyin": "sūn zi", "chinese": "孙子", "pic": "suntzu.jpg" },
		{ "english": "Spider Man", "pinyin": "zhī zhū xiá", "chinese": "蜘蛛侠", "pic": "spiderman.jpg" },
		{ "english": "Darth Vader", "pinyin": "dá sī wéi dá", "chinese": "达斯维达", "pic": "vader.jpg" },
		{ "english": "Gandhi", "pinyin": "gān dì", "chinese": "甘地", "pic": "gandhi.jpg" },
		{ "english": "Mozart", "pinyin": "mò zhā tè", "chinese": "莫扎特", "pic": "mozart.jpg" },
		{ "english": "Curious George", "pinyin": "hàoqí de qiáozhì", "chinese": "好奇的乔治", "pic": "curiousgeorge.jpg" },
		{ "english": "Vladimir Putin", "pinyin": "pǔ jīng", "chinese": "普京", "pic": "putin.jpg" },
		{ "english": "Weird Al", "pinyin": "guài rén ào ěr", "chinese": "怪人奧爾", "pic": "weirdal.jpg" },
	],
	"Singular Pronouns": [
		{ "english": "I", "pinyin": "wǒ", "chinese": "我" },
		{ "english": "You", "pinyin": "nǐ", "chinese": "你" },
		{ "id": "hesheit", "english": "He/She/It", "pinyin": "tā", "chinese": "他" },
	],
	"Plural Pronouns": [
		{ "english": "We", "pinyin": "wǒ men", "chinese": "我们" },
		{ "english": "Y'all", "pinyin": "nǐ men", "chinese": "你们" },
		{ "english": "They", "pinyin": "tā men", "chinese": "他们" },
	],
	"Family": [
		{ 'english': 'Grandpa (paternal)', 'pinyin': 'yé ye', 'chinese': '爷爷' },
		{ 'english': 'Grandma (paternal)', 'pinyin': 'nǎi nai', 'chinese': '奶奶' },
		{ 'english': 'Grandpa (maternal)', 'pinyin': 'wài gōng', 'chinese': '外公' },
		{ 'english': 'Grandma (maternal)', 'pinyin': 'wài pó', 'chinese': '外婆' },
		{ 'english': 'Dad', 'pinyin': 'bà ba', 'chinese': '爸爸' },
		{ 'english': 'Mom', 'pinyin': 'mā ma', 'chinese': '妈妈' },
		{ 'english': 'Older Brother', 'pinyin': 'gē ge', 'chinese': '哥哥' },
		{ 'english': 'Older Sister', 'pinyin': 'jiě jie', 'chinese': '姐姐' },
		{ 'english': 'Younger Brother', 'pinyin': 'dì di', 'chinese': '弟弟' },
		{ 'english': 'Younger Sister', 'pinyin': 'mèi mei', 'chinese': '妹妹' },
	],
	"Names": [
		//{ 'english': 'Allison', 'chinese': '啊栗', 'pinyin': 'ā lì', 'meaning': 'Little Chestnut' },
		//{ 'english': 'Anika', 'chinese': '安安', 'pinyin': 'ān an', 'meaning': 'Peace' },
		//{ 'english': 'Dan', 'chinese': '胆猎', 'pinyin': 'dǎn liè', 'meaning': 'Brave Hunter' },
		{ 'english': 'Levi', 'chinese': '钟昊德', 'pinyin': 'zhōng hào dé', 'meaning': 'Vast Virtue', 'intro': 'wǒ jiào zhōng hào dé.  jīn zhōng zhōng, hào tiān wǎng jí de hào, dào dé de dé.' },
		{ 'english': 'Natalie', 'chinese': '钟丽珠', 'pinyin': 'zhōng lì zhū', 'meaning': 'Beautiful Pearl', 'intro': 'wǒ jiào zhōng lì zhū. jīn zhōng zhōng, měi lì de lì, zhēn zhū de zhū.' },
		{ 'english': 'Sam', 'chinese': '钟海琪', 'pinyin': 'zhōng hǎi qí', 'meaning': 'Ocean Jade', 'intro': 'wǒ jiào zhōng hǎi qí. jīn zhōng zhōng, chūn shēn sì hǎi de hǎi, xiàng qí de qí.' },
		{ 'english': 'Seth', 'chinese': '钟敏良', 'pinyin': 'zhōng mǐn liáng', 'meaning': 'Quick, nimble, agile, clever, smart', 'intro': 'wǒ jiào zhōng mǐn liáng. jīn zhōng zhōng, mǐn ér hào xué de mǐn, zhāng liáng de liáng.' },
		{ 'english': 'Emmett', 'chinese': '钟怡蘑', 'pinyin': 'zhōng yí mó', 'meaning': 'Happy mushroom' },
		//{ 'english': 'Sona', 'chinese': '松松', 'pinyin': 'sōng song', 'meaning': 'Easy Going' },
		{ 'english': 'Walker', 'chinese': '林悟朗', 'pinyin': 'lín wù lǎng', 'meaning': 'Clear/Bright Enlightenment', 'intro': 'wǒ jiào lín wù lǎng. shuāng mù lín, sūn wù kōng de wù, huò rán kāi lǎng de lǎng.' },
		{ 'english': 'Teacher', 'chinese': '钟老师', 'pinyin': 'zhōng lǎo shī', 'meaning': 'Teacher Jones', "cl": "位", "pic": "teacher.jpg" },
		{ 'english': 'Jack', 'chinese': '杜杰克', 'pinyin': 'dù jié kè', 'meaning': 'Jack' },
		//{ 'english': 'Mason', 'chinese': '杜石匠', 'pinyin': 'dù shí jiàng', 'meaning': 'mason' },
		{ 'english': 'Gunnar', 'chinese': '杜炮手', 'pinyin': 'dù pào shǒu', 'meaning': 'gunner' },
		{ 'english': 'Marshall', 'chinese': '杜元帅', 'pinyin': 'dù yuán shuài', 'meaning': 'marshal' },
		{ 'english': 'Hugo', 'chinese': '杜雨果', 'pinyin': 'dù yǔ guǒ', 'meaning': 'Literally: Rain fruit, but really it just means Hugo' }
	],
	"States": [
		{ 'english': 'California', 'pinyin': 'jiā zhōu', 'chinese': '加州' },
		{ 'english': 'Illinois', 'pinyin': 'yī zhōu', 'chinese': '伊州' },
		{ 'english': 'Indiana', 'pinyin': 'yìn dì ān nà zhōu', 'chinese': '印地安那州' },
		{ 'english': 'Florida', 'pinyin': 'fó zhōu', 'chinese': '佛州' },
		{ 'english': 'Missouri', 'pinyin': 'mì zhōu', 'chinese': '密州' },
		{ 'english': 'New York', 'pinyin': 'niǔ zhōu', 'chinese': '纽州' },
		{ 'english': 'Ohio', 'pinyin': 'é zhōu', 'chinese': '俄州' },
		{ 'english': 'Pennsylvania', 'pinyin': 'bīn zhōu', 'chinese': '宾州' },
		{ 'english': 'Texas', 'pinyin': 'dé zhōu', 'chinese': '得州' },
		{ 'english': 'Wisconsin', 'pinyin': 'wēi zhōu', 'chinese': '威州' },
	],
	"Is-Called": [
		{ 'english': 'called', 'pinyin': 'jiào', 'chinese': '叫' },
		{ 'english': 'is', 'pinyin': 'shì', 'chinese': '是' }
	],
	"Colors": [
		{ 'english': 'red', 'hex': '#ff0000', 'pinyin': 'hóng sè', 'chinese': '红色' },
		{ 'english': 'yellow', 'hex': '#ffff00', 'pinyin': 'huáng sè', 'chinese': '黄色' },
		{ 'english': 'blue', 'hex': '#0000ff', 'pinyin': 'lán sè', 'chinese': '蓝色' },
		{ 'english': 'orange', 'hex': '#ff8c00', 'pinyin': 'chéng sè', 'chinese': '橙色' },
		{ 'english': 'green', 'hex': '#008000', 'pinyin': 'lǜ sè', 'chinese': '绿色' },
		{ 'english': 'purple', 'hex': '#800080', 'pinyin': 'zǐ sè', 'chinese': '紫色' },
		{ 'english': 'white', 'hex': '#ffffff', 'pinyin': 'bái sè', 'chinese': '白色' },
		{ 'english': 'black', 'hex': '#000000', 'pinyin': 'hēi sè', 'chinese': '黑色' },
		{ 'english': 'brown', 'hex': '#3b2503', 'pinyin': 'zōng sè', 'chinese': '棕色' },
		{ 'english': 'gray', 'hex': '#808080', 'pinyin': 'huī sè', 'chinese': '灰色' },
		{ 'english': 'pink', 'hex': '#EEA9B8', 'pinyin': 'fěn hóng sè', 'chinese': '粉红色' },
		{ 'english': 'teal', 'hex': '#079690', 'pinyin': 'qīng sè', 'chinese': '青色' },
	],
	"Bu/Mei": [
		{ 'english': 'not', 'pinyin': 'bù', 'chinese': '不', 'no-pre': [ '有' ] },
		{ 'english': 'not', 'pinyin': 'méi', 'chinese': '没' },
	],
	"Verylike": [
		{ 'english': 'a bit', 'pinyin': 'yì diǎn', 'chinese': '一点' },
		{ 'english': 'very', 'pinyin': 'hěn', 'chinese': '很' },
		{ 'english': 'unusually', 'pinyin': 'fēi cháng', 'chinese': '非常' },
		{ 'english': 'too', 'pinyin': 'tài', 'chinese': '太' },
		{ 'english': 'more and more', 'pinyin': 'yuè lái yuè', 'chinese': '越来越' },
	],
	"Thisthat": [
		{ 'english': 'this', 'pinyin': 'zhè', 'chinese': '这' },
		{ 'english': 'that', 'pinyin': 'nà', 'chinese': '那' },
		{ 'english': 'which', 'pinyin': 'nǎ', 'chinese': '哪' },
	],
	"Thisthatge": [
		{ 'english': 'this', 'pinyin': 'zhè ge', 'chinese': '这个' },
		{ 'english': 'that', 'pinyin': 'nà ge', 'chinese': '那个' },
	],
	"Cans": [
		{ 'english': 'can', 'pinyin': 'kě yǐ', 'chinese': '可以' },
		{ 'english': 'can', 'pinyin': 'néng gòu', 'chinese': '能够' },
		{ 'english': 'cannot', 'pinyin': 'bù kě yǐ', 'chinese': '不可以' },
		{ 'english': 'cannot', 'pinyin': 'bù néng gòu', 'chinese': '不能够' },
	],
	"Boy/Girl": [
		{ 'english': 'boy', 'pinyin': 'nán hái zi', 'chinese': '男孩子' },
		{ 'english': 'girl', 'pinyin': 'nǚ hái zi', 'chinese': '女孩子' },
	],
	"School Subjects": [
		{ 'english': 'Art', 'pinyin': 'yì shù', 'chinese': '艺术' },
		{ 'english': 'Biology', 'pinyin': 'shēng wù xué', 'chinese': '生物学' },
		{ 'english': 'Chemistry', 'pinyin': 'huà xué', 'chinese': '化学' },
		{ 'english': 'Chinese', 'pinyin': 'zhōng wén', 'chinese': '中文' },
		{ 'english': 'Computer Science', 'pinyin': 'jì suàn jī kē xué', 'chinese': '计算机科学' },
		{ 'english': 'English', 'pinyin': 'yīng yǔ', 'chinese': '英语' },
		{ 'english': 'Health', 'pinyin': 'jiàn kāng', 'chinese': '健康' },
		{ 'english': 'History', 'pinyin': 'lì shǐ xué', 'chinese': '历史学' },
		{ 'english': 'Math', 'pinyin': 'shù xué', 'chinese': '数学' },
		{ 'english': 'Music', 'pinyin': 'yīn yuè', 'chinese': '音乐' },		
	],
	"New Year": [
		{ 'english': 'fireworks', 'pinyin': 'yàn huǒ', 'chinese': '焰火' },
		{ 'english': 'tradition', 'pinyin': 'cháun tóng', 'chinese': '传统' },
		{ 'english': 'lantern', 'pinyin': 'dēng lóng', 'chinese': '灯笼' },
		{ 'english': 'red packet', 'pinyin': 'hóng bāo', 'chinese': '红包' },
		{ 'english': 'spring festival', 'pinyin': 'chūn jié', 'chinese': '春节' },
		{ 'english': 'dumpling', 'pinyin': 'jiǎo zi', 'chinese': '饺子' },
		{ "english": "rat", "pinyin": "shǔ", "chinese": "鼠", "pic": "rat.jpg" },
		{ 'english': 'new year rice cake', 'pinyin': 'nián gāo', 'chinese': '年糕' },
		{ 'english': 'happy new year 1', 'pinyin': 'gōng xi fā cái', 'chinese': '恭喜发财' },
		{ 'english': 'happy new year 2', 'pinyin': 'xīn nián kuài lè', 'chinese': '新年快乐' },
	],
	"Holidays": [
		{ "english": "Thanksgiving", "pinyin": "gǎn ēn jié", "chinese": "感恩节", "pic": "thanksgiving.gif" },
		{ "english": "Christmas", "pinyin": "shèng dàn jié", "chinese": "圣诞节", "pic": "christmas.jpg" },
		{ "english": "Easter", "pinyin": "fù huó jié", "chinese": "复活节", "pic": "easter.jpg" },
		{ "english": "Valentine's Day", "pinyin": "qíng rén jié", "chinese": "情人节", "pic": "valentines.jpg" },
		{ "english": "Mother's Day", "pinyin": "mǔ qīn jié", "chinese": "母亲节", "pic": "mothersday.jpg" },
		{ "english": "Father's Day", "pinyin": "fù qīn jié", "chinese": "父亲节", "pic": "fathersday.jpg" },
		{ "english": "Halloween", "pinyin": "wàn shèng jié", "chinese": "万圣节", "pic": "halloween.jpg" },
		{ "english": "Independence Day", "pinyin": "dú lì rì", "chinese": "独立日", "pic": "july4.png" },
		{ "english": "New Year", "pinyin": "xīn nián", "chinese": "新年", "pic": "newyear.jpg" },
		{ "english": "Chinese New Year", "pinyin": "chūn jié", "chinese": "春节", "pic": "fu.jpg" }
	],
	"Relative Days": [
		{ "english": "Today", "pinyin": "jīn tiān", "chinese": "今天" },
		{ "english": "Tomorrow", "pinyin": "míng tiān", "chinese": "明天" },
		{ "english": "Day after tomor.", "pinyin": "hòu tiān", "chinese": "后天" },
		{ "english": "Yesterday", "pinyin": "zuó tiān", "chinese": "昨天" },
		{ "english": "Day before yest.", "pinyin": "qián tiān", "chinese": "前天" }
	]
};

export let SingleWords = {
	'de': { 'english': 'de', 'pinyin': 'de', 'chinese': '的' },
	'le': { 'english': 'le', 'pinyin': 'le', 'chinese': '了' },
	'ge': { 'english': 'ge', 'pinyin': 'ge', 'chinese': '个' },
	'ma': { 'english': '?', 'pinyin': 'ma', 'chinese': '吗' },
	'bei': { 'english': 'received', 'pinyin': 'bèi', 'chinese': '被' },
	'age': { 'english': 'years old', 'pinyin': 'suì', 'chinese': '岁' },
	'animal': { 'english': 'animal', 'pinyin': 'dòng wù', 'chinese': '动物' },
	'at': { 'english': 'at', 'pinyin': 'zài', 'chinese': '在' },	
	'born': { 'english': 'born', 'pinyin': 'chū shēng', 'chinese': '出生' },
	'color': { 'english': 'color', 'pinyin': 'yán sè', 'chinese': '颜色' },	
	'favorite': { 'english': 'favorite', 'pinyin': 'zuì xǐ huān', 'chinese': '最喜欢' },
	'food': { 'english': 'food', 'pinyin': 'shí wù', 'chinese': '食物' },	
	'give': { 'english': 'give', 'pinyin': 'gěi', 'chinese': '给' },
	'is': { 'english': 'is', 'pinyin': 'shì', 'chinese': '是' },	
	'meat': { 'english': 'meat', 'pinyin': 'ròu', 'chinese': '肉' },
	'please': { 'english': 'please', 'pinyin': 'qǐng', 'chinese': '请' },
	'this': { 'english': 'this', 'pinyin': 'zhè', 'chinese': '这' },
	'that': { 'english': 'that', 'pinyin': 'nà', 'chinese': '那' },
	'who': { 'english': 'who', 'pinyin': 'sheí', 'chinese': '谁' },
	'live': { 'english': 'live', 'pinyin': 'zhù', 'chinese': '住' },
	'andthen': { 'english': 'and then', 'pinyin': 'rán hòu', 'chinese': '然后' },
	'backyard': { 'english': 'backyard', 'pinyin': 'hòu yuàn', 'chinese': '后院' },
	'my': { 'english': 'my', 'pinyin': 'wǒ de', 'chinese': '我的' },	
	'friend': { 'english': 'friend', 'pinyin': 'péng yǒu', 'chinese': '朋友' },
	'drop': { 'english': 'drop', 'pinyin': 'diào', 'chinese': '掉' },
	'ground': { 'english': 'ground', 'pinyin': 'dì shàng', 'chinese': '地上' },
	'care': { 'english': 'care', 'pinyin': 'zài hū', 'chinese': '在乎' },
	'pickup': { 'english': 'pick up', 'pinyin': 'ná qǐ', 'chinese': '拿起' },
	'zoo': { 'english': 'zoo', 'pinyin': 'dòng wù yuán', 'chinese': '动物园' },
	'and': { 'english': 'and', 'pinyin': 'hé', 'chinese': '和' },
	'new': { 'english': 'new', 'pinyin': 'xīn', 'chinese': '新' },
	'thisyear': { 'english': 'this year', 'pinyin': 'jīn nián', 'chinese': '今年' },
	'couple': { 'english': 'couple', 'pinyin': 'liǎng', 'chinese': '两' },
	'teach': { 'english': 'teach', 'pinyin': 'jiào', 'chinese': '教' },
	'compare': { 'english': 'compare', 'pinyin': 'bǐ', 'chinese': '比' },
	'never': { 'english': 'never', 'pinyin': 'méi', 'chinese': '没' },
	'past': { 'english': 'past', 'pinyin': 'guò', 'chinese': '过' },
	'wantornot': { 'english': 'want/not want', 'pinyin': 'yào bú yào', 'chinese': '要不要' },
	'atthattime': { 'english': 'at that time', 'pinyin': 'de shí hòu', 'chinese': '的时候' },
	'but': { 'english': 'but', 'pinyin': 'dàn shì', 'chinese': '但是' },
	'mei': { 'english': 'not', 'pinyin': 'méi', 'chinese': '没' },
	'jiu': { 'english': 'then', 'pinyin': 'jiù', 'chinese': '就' },
};